### ISSUE TITLE
⚙️ Build: Subquery manifest

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/subql-okp4#71]
The subquery manifest need to be reviewed to make sure subquery is set up correctly. See [official documentation](https://academy.subquery.network/build/manifest/cosmos.html)

**Comment by ccamel** [comment]
Pretty sure it's already addressed by the [lint-subql-project job](https://github.com/okp4/subql-okp4/blob/main/.github/workflows/lint.yml#L102).

**Comment by ErikssonJoakim** [comment]
@ccamel Sorry the description might be a bit vague this issue is to review the manifest configurations like version handling, how to handle the startblock etc.

**Comment by ccamel** [comment]
Oh, sure. I see your point. I believe this should also be considered in the context of releases and deployments.

**Comment by ccamel** [comment]
Implemented with https://github.com/okp4/subql-okp4/pull/152.
