### ISSUE TITLE
⚙️ Build: Linters

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/subql-okp4#73]
We need to review the configuration of the linters **eslint**, **yamllint**, **markdownlint**. Things to consider:

- Coherence
- Developer experience (DX)
- Compatibility issues
- Code security
- Code formatting

**Comment by ccamel** [comment]
Done with:
- https://github.com/okp4/subql-okp4/pull/66
- https://github.com/okp4/subql-okp4/pull/66

The tightening of the configuration of code quality verification tools can be considered on a case-by-case basis.
